config/routes.rb
MobilePhone::Application.routes.draw do
  get "cart/new"

  get "cart/new"
  resources :sessions
  resources :orders
  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "customers#new", :as => "sign_up"

  get "log_out" => "sessions#destroy", :as => "log_out"

  get "pages/Home"

  get "pages/AboutUs"

  get "pages/ContactUs"

  get "pages/PrivacyPolicy"

  resources :customers
  resources :phones

  root :to => 'pages#Home'
  match 'orders/new/:id' => 'orders#new'
  match 'pages/AboutUs' => 'pages#aboutus'
  match 'pages/ContactUs' => 'pages#contactus'
  match 'pages/PrivacyPolicy' => 'pages#privacypolicy'

end

app/models/phone.rb
class Phone < ActiveRecord::Base
	mount_uploader :photo, PhotoUploader

	validates :brand, :presence => true
  	validates :name, :presence => true
  	validates :price, :presence => true
  	validates :quantityInStock, :presence => true
  	validates_numericality_of :quantityInStock, :greater_than_or_equal_to => 0, :only_integer => true
  	validates_numericality_of :price, :greater_than => 0.0
    scope :exsitedPhones, :conditions => ['id = ?', 'true']

  	has_many :orders
  	validates_numericality_of :quantityInStock, :greater_than_or_equal_to => 0, :only_integer => true
  	validates_numericality_of :price, :greater_than => 0.0

end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @phones }
    end
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
    @phone = Phone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phone }
    end
  end

  # GET /phones/new
  # GET /phones/new.json
  def new
    @phone = Phone.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phone }
    end
  end

  # GET /phones/1/edit
  def edit
    @phone = Phone.find(params[:id])
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(params[:phone])

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render json: @phone, status: :created, location: @phone }
      else
        format.html { render action: "new" }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /phones/1
  # PUT /phones/1.json
  def update
    @phone = Phone.find(params[:id])

    respond_to do |format|
      if @phone.update_attributes(params[:phone])
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone = Phone.find(params[:id])
    @phone.destroy

    respond_to do |format|
      format.html { redirect_to phones_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/_form.html.erb
<%= form_for @phone, :html => { :multipart => true } do |f| %>
  <% if @phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% @phone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>

  <div class="field">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantityInStock %><br />
    <%= f.number_field :quantityInStock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phones/edit.html.erb
<h1>Editing phone</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone %> |
<%= link_to 'Back', phones_path %>

app/views/phones/index.html.erb
<h1>Listing phones</h1>

<table>
  <tr>
    <th>Photo</th>
    <th>ID</th>
    <th>Brand</th>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Quantityinstock</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @phones.each do |phone| %>
  <tr>
    <td><%= image_tag phone.photo_url %></td>
    <td><%= phone.id %></td>
    <td><%= phone.brand %></td>
    <td><%= phone.name %></td>
    <td><%= phone.description %></td>
    <td><%= phone.price %></td>
    <td><%= phone.quantityInStock %></td>
    <td><%= link_to 'Buy', :controller => :orders, :action => :new, :id => phone.id %></td>
    <% if signed_in? %>
		<td><%= link_to 'Buy', :controller => :orders, :action => :new, :id => phone.id %></td>
    <td><%= link_to 'Show', phone %></td>
		
	<% else %>
	
    <td><%= link_to 'Show', phone %></td>
	<% end %>
	</tr>
<% end %>
</table>

<br />

<%= link_to 'New Phone', new_phone_path %>

app/views/phones/new.html.erb
<h1>New phone</h1>

<%= render 'form' %>

<%= link_to 'Back', phones_path %>

app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>
  
<p>
<% unless @phone.photo_url.nil? %>
  <p><%= image_tag @phone.photo_url%></p>
<% end %>
</p>

<p>
  <b>Brand:</b>
  <%= @phone.brand %>
</p>

<p>
  <b>Name:</b>
  <%= @phone.name %>
</p>

<p>
  <b>Description:</b>
  <%= @phone.description %>
</p>

<p>
  <b>Price:</b>
  <%= @phone.price %>
</p>

<p>
  <b>Quantityinstock:</b>
  <%= @phone.quantityInStock %>
</p>


<%= link_to 'Edit', edit_phone_path(@phone) %> |
<%= link_to 'Back', phones_path %>