config/routes.rb
MobilePhone::Application.routes.draw do
  get "cart/new"

  get "cart/new"
  resources :sessions
  resources :orders
  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "customers#new", :as => "sign_up"

  get "log_out" => "sessions#destroy", :as => "log_out"

  get "pages/Home"

  get "pages/AboutUs"

  get "pages/ContactUs"

  get "pages/PrivacyPolicy"

  resources :customers
  resources :phones

  root :to => 'pages#Home'
  match 'orders/new/:id' => 'orders#new'
  match 'pages/AboutUs' => 'pages#aboutus'
  match 'pages/ContactUs' => 'pages#contactus'
  match 'pages/PrivacyPolicy' => 'pages#privacypolicy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobilePhone</title>
<<<<<<< HEAD
  <%= stylesheet_link_tag    "style", :media => "all" %>
=======
  <%= stylesheet_link_tag    "application", :media => "all" %>
>>>>>>> f2b71379402b811315b12b76aa38be4b48e37f2a
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
	<a class="btn btn-navbar">
<<<<<<< HEAD
	<%= render 'partials/header' %>
=======
		<% if signed_in? %>
		Logged in as <%= @current_customer.email %>
		<%= link_to "Log out", log_out_path %>
	<% else %>
		<%= link_to "Sign up", sign_up_path %> or
		<%= link_to "Log in", log_in_path %>
	<% end %>	
>>>>>>> f2b71379402b811315b12b76aa38be4b48e37f2a
			<div class="navbar navbar-fixed-top">
			  <div class="navbar-inner">
			    <div class="container">
			      <a class="brand" href="/">Phone Retailer</a>
			      	<ul class="nav">
			        	<li class="active"><a href="/">Home</a></li>
			      	<!-- </ul>
			      	<ul class="nav pull-right"> -->
					<% if signed_in? %>
						<li><%= link_to "Log out", log_out_path %></li>
				        <li><a href="/log_out">Log Out</a></li>
					<% else %>
			        	<li><%= link_to "Sign up", sign_up_path %></li>
			        	<li><%= link_to "Log in", log_in_path %></li>
					<% end %>
			      </ul>
			    </div>
			  </div>
			</div>
			
			
			
</div>
</div>
</div>

<% flash.each do |name, msg| %>
	<% content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>


<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>
<<<<<<< HEAD
    
<%= render 'partials/footer' %> 
=======
    <div class="span3">
      <h2>About Us</h2>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </div>
>>>>>>> f2b71379402b811315b12b76aa38be4b48e37f2a
  </div>
</div>

</body>
</html>